"""Extract Chapter 0 inputs from saved sources; no physics or visual styling.

Run from any directory: python3 scripts/prepare-ch00-data.py
Raw snapshots remain research evidence; their presence does not clear reuse.
"""
import csv
import hashlib
import json
import re
import subprocess
import warnings
from pathlib import Path

import openpyxl
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / 'data/ch00/raw'
OUT = ROOT / 'data/ch00/processed'
ACCESS = '2026-10-06'
NREL_NOTICE = '''The National Renewable Energy Laboratory (NREL) is operated for the U.S. Department of Energy (DOE) by Alliance for Sustainable Energy, LLC (\"Alliance\").
Unless data or software is explicitly made available on this server under separate license terms (in which case such license terms shall apply only to such data or software), access to or use of any data or software made available on this server (\"Data\") shall impose the following obligations on the user, and use of the Data constitutes user's agreement to these terms. The user is granted the right, without any fee or cost, to use or copy the Data, provided that this entire notice appears in all copies of the Data. Further, the user agrees to credit DOE/NREL/ALLIANCE in any publication that results from the use of the Data. The names DOE/NREL/ALLIANCE, however, may not be used in any advertising or publicity to endorse or promote any products or commercial entities unless specific written permission is obtained from DOE/NREL/ ALLIANCE. The user also understands that DOE/NREL/ALLIANCE are not obligated to provide the user with any support, consulting, training or assistance of any kind with regard to the use of the Data or to provide the user with any updates, revisions or new versions thereof. DOE, NREL, and ALLIANCE do not guarantee or endorse any results generated by use of the Data, and user is entirely responsible for the results and any reliance on the results or the Data in general.
USER AGREES TO INDEMNIFY DOE/NREL/ALLIANCE AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, AGENTS, AND EMPLOYEES AGAINST ANY CLAIM OR DEMAND, INCLUDING REASONABLE ATTORNEYS' FEES, RELATED TO USER'S USE OF THE DATA. THE DATA ARE PROVIDED BY DOE/NREL/ALLIANCE \"AS IS,\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. DOE/NREL/ALLIANCE ASSUME NO LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS, OR USEFULNESS OF THE DATA, OR REPRESENT THAT ITS USE WOULD NOT INFRINGE PRIVATELY OWNED RIGHTS. IN NO EVENT SHALL DOE/NREL/ALLIANCE BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER, INCLUDING BUT NOT LIMITED TO CLAIMS ASSOCIATED WITH THE LOSS OF DATA OR PROFITS, THAT MAY RESULT FROM AN ACTION IN CONTRACT, NEGLIGENCE OR OTHER TORTIOUS CLAIM THAT ARISES OUT OF OR IN CONNECTION WITH THE ACCESS, USE OR PERFORMANCE OF THE DATA.'''

def read(name):
    return json.loads((RAW / name).read_text())


def write(name, value):
    (OUT / name).write_text(json.dumps(value, indent=2, ensure_ascii=False) + '\n')


def table(name, rows, preamble=None):
    with (OUT / name).open('w', newline='') as f:
        if preamble:
            f.write('\n'.join('# ' + line for line in preamble.splitlines()) + '\n')
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def history_from_pdf():
    """Reuse extracted numbers, or extract them from a local report if present."""
    extracted = RAW/'iaea-history-1954-2024.json'
    if extracted.exists():
        return
    pdf = RAW/'iaea-reactors-2025.pdf'
    text = subprocess.run(['pdftotext','-layout',str(pdf),'-'],check=True,
                          capture_output=True,text=True).stdout
    start = text.index('TABLE 7. ANNUAL CONSTRUCTION')
    end = text.index('TABLE 8.',start)
    rows = []
    names = ['year','construction_starts','construction_MWe','grid_connections',
             'grid_MWe','operating_units','operating_MWe']
    for line in text[start:end].splitlines():
        if not re.match(r'^\s+\d{4}\s',line):continue
        columns = [(0,20),(20,35),(35,53),(53,68),(68,86),(86,102),(102,len(line))]
        values = [int(line[a:b].strip()) if line[a:b].strip() else 0 for a,b in columns]
        rows.append(dict(zip(names,values)))
    assert [r['year'] for r in rows] == list(range(1954,2025)), 'Unexpected IAEA table format'
    (RAW/'iaea-history-1954-2024.json').write_text(json.dumps({
        'source_url':'https://www-pub.iaea.org/MTCD/Publications/PDF/RDS-2-45_web.pdf',
        'table':7,'access_date':ACCESS,'licence_status':'No explicit CC licence found; research evidence; numerical facts only',
        'transformation':'pdftotext -layout; Table 7 fixed-width numeric fields; blanks become zero',
        'rows':rows},indent=2)+'\n')


def build():
    OUT.mkdir(parents=True, exist_ok=True)
    history_from_pdf()
    countries = {r['id'] for r in read('wb_countries.json')[1]
                 if r['region']['id'] != 'NA'}
    gdp = {r['countryiso3code']: r['value'] for r in read('wb_gdp_ppp.json')[1]
           if r['date'] == '2024' and r['value'] is not None}
    pop = {r['countryiso3code']: r['value'] for r in read('wb_population.json')[1]
           if r['date'] == '2024' and r['value'] is not None}
    rows, excluded = [], []
    for r in read('eia_2024.json')['response']['data']:
        if r['countryRegionTypeId'] != 'c':
            continue
        iso = r['countryRegionId']
        reasons = []
        if iso not in countries: reasons.append('not a World Bank country/economy')
        if not gdp.get(iso): reasons.append('GDP PPP unavailable/nonpositive')
        if not pop.get(iso): reasons.append('population unavailable/nonpositive')
        try: energy = float(r['value'])
        except (TypeError, ValueError): energy = 0
        if energy <= 0: reasons.append('energy unavailable/nonpositive')
        if reasons:
            excluded.append({'iso3': iso, 'name': r['countryRegionName'], 'reason': '; '.join(reasons)})
        else:
            rows.append({'iso3': iso, 'country': r['countryRegionName'], 'year': 2024,
                         'primary_energy_QBTU': r['value'], 'population': pop[iso],
                         'gdp_ppp_per_person_2021_international_dollar': gdp[iso]})
    table('energy-gdp-input.csv', sorted(rows, key=lambda r: r['iso3']))
    write('energy-gdp-exclusions.json', excluded)
    balance = read('austria_2025_cells.json')
    table('austria-balance-TJ.csv', [
        {'row': i+1, 'item': row[0], 'year': 2025, **{
            balance[1][j]: row[j] for j in range(1, 38)}}
        for i, row in enumerate(balance) if 2 <= i <= 18])
    write('austria-balance.json', {'year': 2025, 'status': 'preliminary',
        'population': json.loads((ROOT/'data/energy.json').read_text())['austria_2025']['population_annual_average'],
        'headers': balance[1][:38], 'rows': {str(i+1): row[:38] for i, row in enumerate(balance) if 2 <= i <= 18}})
    income_levels = read('gapminder_income_levels_2017.json')
    table('income-levels-2017.csv', [dict(level=r['level'], income_threshold=r['income_threshold'],
        currency_unit=income_levels['currency_unit'], population_billions=r['population_billions'],
        year=income_levels['year'], source='gapminder_income_levels',
        licence_status=income_levels['licence']) for r in income_levels['levels']])
    inputs = {}
    def add(key, value, unit, year, source, notes=''):
        inputs[key] = dict(value=value, unit=unit, year=year, source=source, notes=notes)
    add('world_population', pop['WLD'], 'person', 2024, 'wb_population')
    add('world_population_2025', next(r['value'] for r in read('wb_population.json')[1]
        if r['countryiso3code']=='WLD' and r['date']=='2025'), 'person', 2025, 'wb_population')
    add('austria_population', json.loads((ROOT/'data/energy.json').read_text())['austria_2025']['population_annual_average'], 'person', 2025, 'stat_population', 'Annual average, not year-end.')
    add('austria_area', 83884, 'km^2', 2024, 'bml_area')
    add('austria_gdp', next(r['value'] for r in read('wb_austria_gdp_eur.json')[1] if r['date']=='2025'), 'EUR/(person year)', 2025, 'wb_gdp_austria')
    add('btu_IT', '1055.05585262', 'J', 'definition', 'nist_units', 'Energy corresponding to one International Table Btu.')
    add('seconds_per_year', 31536000, 's/year', 'model', 'assumptions', '365-day engineering year throughout; calendar 2024 is leap year.')
    add('solar_noon', 1000, 'W/m^2', 'model', 'assumptions', 'STC reference irradiance; not a measured Graz noon average.')
    add('pv_efficiency', 0.20, '1', 'model', 'assumptions', 'Assumed module efficiency at STC.')
    add('graz_latitude', 47.0707, 'degree', '2005–2023', 'pvgis')
    add('obliquity', 23.44, 'degree', 'model', 'assumptions', 'Simple declination model, ignoring Earth-orbit eccentricity.')
    add('park_area', 1.64, 'km^2', 2021, 'enbw_weesow')
    add('park_peak', 187, 'MWp', 2021, 'enbw_weesow')
    add('park_annual_energy', 180, 'GWh/year', 2021, 'enbw_weesow', 'Operator expectation, NOT measured annual generation.')
    add('hornsrev_area', 20, 'km^2', ACCESS, 'vattenfall_hornsrev')
    add('hornsrev_peak', 158, 'MW', ACCESS, 'vattenfall_hornsrev', 'Current operator factbox; original design was 160 MW.')
    add('eu_onshore_cf', .23, '1', 2024, 'windeurope')
    add('eu_offshore_cf', .35, '1', 2024, 'windeurope')
    add('eu_new_onshore_cf_low', .30, '1', 2024, 'windeurope', 'Estimate for new farms; not operating-fleet observation.')
    add('eu_new_onshore_cf_high', .35, '1', 2024, 'windeurope')
    add('eu_new_offshore_cf_low', .42, '1', 2024, 'windeurope')
    add('eu_new_offshore_cf_high', .55, '1', 2024, 'windeurope')
    add('austria_wind_capacity', 4221, 'MW', 2025, 'igwind', 'Year-end installed capacity; CF computed with this is only a proxy.')
    add('us_wind_density', .90, 'W/m^2', 2016, 'miller_corrigendum', 'Corrected capacity-weighted 430-plant sample; Voronoi footprint.')
    add('us_solar_density', 5.7, 'W/m^2', 2016, 'miller_corrigendum', 'Corrected 1047-plant sample; footprint methodology differs from wind.')
    add('nuclear_efficiency', .33, '1', 'model', 'wna_fuel')
    add('nuclear_burnup', 45, 'GW day/t', 'model', 'wna_fuel')
    add('enrichment_product', .045, '1', 'model', 'wna_fuel')
    add('enrichment_feed', .00711, '1', 'model', 'wna_fuel')
    add('enrichment_tails', .0022, '1', 'model', 'wna_fuel')
    add('nuclear_capacity_factor', .90, '1', 'model', 'assumptions')
    add('deployment_horizon', 30, 'year', 'model', 'assumptions')
    add('historical_grid_connections', 33, 'reactor/year', '1984 and 1985', 'iaea_history', 'Maximum in IAEA 2025 table 7 covering 1954–2024.')
    add('historical_construction_starts', 43, 'reactor/year', 1976, 'iaea_history', 'Different event from first grid connection.')
    add('goesgen_net_power', 1010, 'MW(e)', ACCESS, 'kkg')
    add('dt_energy', 17.6, 'MeV/reaction', 'physical value', 'iaea_fusion')
    add('elementary_charge', '1.602176634e-19', 'C', 2019, 'nist_constants', 'Exact SI eV conversion.')
    add('atomic_mass', '1.66053906892e-27', 'kg', 2022, 'nist_constants', 'Mass corresponding to one unified atomic mass unit (1 u).')
    add('deuterium_atomic_mass', '2.01410177812', 'u', 'NIST isotopes', 'nist_isotopes')
    add('tritium_atomic_mass', '3.0160492779', 'u', 'NIST isotopes', 'nist_isotopes')
    add('coal_heat', 24, 'MJ/kg', 'model', 'assumptions', 'Illustrative coal lower heating value, not universal.')
    add('ocean_volume', 1.335e9, 'km^3', ACCESS, 'noaa_ocean')
    add('seawater_density', 1025, 'kg/m^3', 'model', 'assumptions')
    add('seawater_water_fraction', .965, '1', 'model', 'assumptions', '35 g/kg salinity model.')
    add('water_molecular_mass', '18.01528', 'u', 'model', 'nist_isotopes')
    add('deuterium_hydrogen_ratio', '155.76e-6', '1', 'VSMOW standard', 'nist_vsmow', 'D/H atomic ratio; not a mass fraction.')
    add('lithium_reserves', 37000000, 't Li', 2025, 'usgs_lithium')
    add('lithium_production', 290000, 't Li/year', 2025, 'usgs_lithium', 'Excludes withheld US production.')
    add('uranium_identified', 7934500, 't U', '2023-01-01', 'redbook', 'RAR + inferred, recoverable below USD 260/kg; resources, not reserves.')
    add('uranium_identified_130', 5925700, 't U', '2023-01-01', 'redbook')
    add('uranium_production_2023', 54345, 't U/year', 2023, 'redbook', 'Reported/provisional 2023 production in 2024 Red Book.')
    add('sustainable_horizon', 1000, 'year', 'model', 'assumptions', 'Finite inventory divided over horizon; not sustainability certification.')
    add('legacy_world_population', 1e10, 'person', 2025, 'legacy_handwriting', 'Teaching assumption, not actual 2025 population.')
    add('legacy_daily_demand', 100, 'kWh/(person day)', 2025, 'legacy_handwriting', 'World stock-lifetime teaching demand on pp.14/29.')
    add('legacy_coal_stock', 1e15, 'kg', 2025, 'legacy_handwriting')
    add('legacy_coal_heat', 10, 'kWh/kg', 2025, 'legacy_handwriting')
    add('legacy_uranium_stock', 1e10, 'kg', 2025, 'legacy_handwriting')
    add('legacy_uranium_heat', 1e7, 'kWh/kg', 2025, 'legacy_handwriting', 'Near-complete fission potential; NOT once-through LWR.')
    add('corn_yield', 179.3, 'bushel/(acre year)', 2024, 'usda_corn', 'US corn average yield; illustrative crop-to-ethanol chain, not an Austrian field measurement.')
    add('ethanol_yield', 2.8, 'gal/bushel', 2024, 'doe_ethanol', 'Dry-mill output; coproduct allocation is not included.')
    add('ethanol_lhv', 76330, 'Btu/gal', 'definition', 'doe_ethanol', 'Pure ethanol lower heating value; gross fuel energy before process inputs.')
    specs = [('oil_stock','A-10 ','C', 'Mt'), ('oil_production','A-11 ','H','Mt/year'),
             ('gas_stock','A-17 ','C','billion m^3'), ('gas_production','A-18 ','H','billion m^3/year'),
             ('hardcoal_stock','A-23 ','D','Mt'), ('hardcoal_production','A-23 ','C','Mt/year'),
             ('lignite_stock','A-30 ','D','Mt'), ('lignite_production','A-30 ','C','Mt/year'),
             ('uranium_lowcost_stock','A-35 ','E','kt U'), ('uranium_production','A-35 ','C','kt U/year')]
    bgr_snapshot = OUT/'bgr-inputs.json'
    if (RAW/'bgr_2025.xlsx').exists():
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            workbook = openpyxl.load_workbook(RAW/'bgr_2025.xlsx', data_only=True)
        bgr_values = {}
        for key,prefix,column,unit in specs:
            sheet = workbook[next(n for n in workbook.sheetnames if n.startswith(prefix))]
            row = next(r[1].row for r in sheet if r[1].value == 'Welt')
            note=f'{sheet.title}!{column}{row}; source attributed in our original data plot under lecturer data-reuse policy; not represented as CC-licensed.'
            bgr_values[key]=dict(value=sheet[f'{column}{row}'].value,unit=unit,year=2024,source='bgr',notes=note)
        write('bgr-inputs.json',bgr_values)
    elif bgr_snapshot.exists():
        bgr_values=json.loads(bgr_snapshot.read_text())
    else:
        raise FileNotFoundError('BGR source workbook or extracted data/ch00/processed/bgr-inputs.json is required.')
    for key,entry in bgr_values.items():
        add(key,entry['value'],entry['unit'],entry['year'],entry['source'],entry['notes'])
    for name, ej in [('oil',10549),('gas',7893),('hardcoal',19908),('lignite',3593),('uranium_lowcost',590)]:
        add(f'{name}_stock_energy', ej, 'EJ', 2024, 'bgr', 'Published summary rounded energy-equivalent reserve; uranium uses BGR conventional-cycle basis.')
    write('inputs.json', inputs)
    write('legacy-estimates.json', {'source':'legacy_handwriting', 'page':10,
        'unit':'kWh/(person day)', 'components':{'Home electricity':5,'Heating / hot water':20,
        'Car':20,'Bus / train / plane':10,'Things':20,'Work / industry':45},
        'gdp_EUR_per_person_year':60000,'intensity_kWh_per_EUR':1,
        'car_example':{'kWh_per_litre':10,'litres_per_100km':5,'km_per_day':30},
        'notes':'Transcribed from rendered handwriting; components are estimates, not independent sectors. Car example gives 15 rather than rounded 20.'})
    write('access.json', [{'series':'electricity','source':'wb_electricity','year':int(r['date']),'value':r['value'],
        'unit':'% of world population','licence_status':'CC BY 4.0'}
        for r in read('wb_electricity.json')[1] if r['value'] is not None and r.get('countryiso3code')=='WLD'])
    land = {}
    for filename, column, key in [
        ('arable-land-use-per-person.csv','Arable land (hectares per person)','faostat_arable'),
        ('cropland-per-person-over-the-long-term.csv','Land use (per capita): Cropland','hyde_cropland')]:
        for row in csv.DictReader((RAW/filename).open()):
            if row['Entity'] in ('World','Austria') and row['Year']=='2023':
                land.setdefault((row['Code'],row['Entity']), {'iso3':row['Code'],'place':row['Entity'],'year':2023})
                land[(row['Code'],row['Entity'])][key+'_ha_person']=float(row[column])
    table('land-use.csv', [dict(row, source='FAO via World Bank / PBL HYDE 3.5 via OWID',
        licence_status='FAO CC BY 4.0; OWID processing CC BY 4.0; HYDE source credited, no separate licence asserted')
        for _,row in sorted(land.items())])
    risk = [
        {'cause':'Free-ranging domestic cats','low':1.3e9,'high':4.0e9,'median':'','unit':'birds/year','year':'2013 corrected','scope':'contiguous United States','source':'loss_cats'},
        {'cause':'Building collisions','low':365e6,'high':988e6,'median':599e6,'unit':'birds/year','year':2014,'scope':'United States','source':'loss_buildings'},
        {'cause':'Vehicle collisions','low':89e6,'high':340e6,'median':'','unit':'birds/year','year':2014,'scope':'United States roads','source':'loss_vehicles'},
        {'cause':'Power lines, collision + electrocution','low':12e6,'high':64e6,'median':'','unit':'birds/year','year':2014,'scope':'United States','source':'loss_powerlines'},
        {'cause':'Wind turbine collisions, monopole estimate','low':140438,'high':327586,'median':234012,'unit':'birds/year','year':2013,'scope':'contiguous United States','source':'loss_wind'},
        {'cause':'European wind-farm fatality rate (median)','low':'','high':'','median':6.5,'unit':'birds/turbine/year','year':'2012 review','scope':'surveyed European wind farms','source':'naturvardsverket_birds'},
    ]
    table('wildlife-risk.csv', risk)
    deaths = []
    for row in csv.DictReader((RAW/'death-rates-from-energy-production-per-twh.csv').open()):
        deaths.append({'source_type':row['Entity'],'year':int(row['Year']),
            'deaths_per_TWh':float(row['Deaths per terawatt-hour of energy production']),
            'unit':'deaths/TWh electricity','source':'owid_deaths',
            'licence_status':'OWID compilation CC BY 4.0; source methods combine heterogeneous air-pollution and accident estimates'})
    table('energy-deaths-per-TWh.csv', deaths)
    workbook_path=RAW/'nrel-lifecycle-emissions-2026.xlsx'
    selected = {'Coal (All Technologies)':'Coal','NGCC':'Natural gas (NGCC)',
        'Photovoltaic (All Technologies)':'Solar PV','Wind (All Technologies)':'Wind',
        'Nuclear - Light Water Reactor (LWR)':'Nuclear (LWR)',
        'Geothermal (All Technologies)':'Geothermal','Hydropower (All Technologies)':'Hydropower',
        'Concentrating Solar Power (Trough and Tower)':'Concentrating solar power',
        'Oil':'Oil'}
    if workbook_path.exists():
        nrel = openpyxl.load_workbook(workbook_path, data_only=True).active
        lifecycle=[]
        for row in nrel.iter_rows(min_row=4, values_only=True):
            if row[1] not in selected:continue
            # Columns W, Y, AA are total lifecycle minimum, median and maximum.
            lifecycle.append({'technology':selected[row[1]],'min_gCO2eq_kWh':row[22],
                'median_gCO2eq_kWh':row[24],'max_gCO2eq_kWh':row[26],
                'unit':'g CO2-eq/kWh electricity','source':'nrel_lifecycle',
                'licence_status':'DOE/NREL/ALLIANCE terms; full notice in CSV preamble; publication credit required; no CC licence asserted'})
        assert len(lifecycle)==len(selected), 'NREL lifecycle table changed format or selected technology labels'
    else:
        cached=OUT/'lifecycle-emissions.csv'
        if not cached.exists():
            raise FileNotFoundError('NREL source workbook is private/ignored; provide the reusable processed lifecycle-emissions.csv snapshot')
        with cached.open() as stream:
            lifecycle=list(csv.DictReader(line for line in stream if not line.startswith('#')))
        assert len(lifecycle)==len(selected), 'Cached NREL lifecycle series is incomplete'
    table('lifecycle-emissions.csv',lifecycle,preamble=NREL_NOTICE)
    (OUT/'nrel-lifecycle-notice.txt').write_text(NREL_NOTICE+'\n')
    prices = list(csv.DictReader((RAW/'solar-pv-prices.csv').open()))
    table('pv-module-prices.csv', [{'year':r['Year'],'USD_2025_per_Wp':r['Solar PV module cost'],
        'source':'owid_prices','licence_status':'OWID CC BY 4.0; source attribution: Nemet/Farmer-Lafond through 2009; IRENA 2025 / pvXchange attributed reuse 2010 onward'} for r in prices])
    write('pv-capacity.json', {'source':'irena_capacity','unit':'MW','year_end':True,
        'licence_status':'IRENA 2026 publication permits free reuse with attribution; © IRENA 2026',
        'years':list(range(2016,2026)), 'world_PV':[293159,386711,481485,583393,714728,859674,1051471,1415161,1872813,2383162],
        'austria_PV':[1103,1276,1462,1710,2051,2791,3800,6394,8904,10304],
        'notes':'Explicit Solar photovoltaic table, not OWID total-solar slug which also includes CSP. IRENA Renewable capacity statistics March 2026 pp. 38–42.'})
    photos = read('photos.json')
    for photo in photos:
        original = ROOT/'slides/photos/originals'/photo['file']
        if original.exists():
            photo['sha256_original'] = hashlib.sha256(original.read_bytes()).hexdigest()
            photo['original_pixels'] = list(Image.open(original).size)
    write('photos.json', photos)
    print(f'Prepared {len(rows)} country observations; {len(excluded)} excluded; {len(inputs)} input constants.')


if __name__ == '__main__':
    build()
